version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # create whl and use pipenv to install dependencies
            sudo apt update && sudo apt upgrade -y && sudo apt install -y git
            sudo pip install setuptools --upgrade
            sudo pip install --upgrade pip
            sudo pip install pipenv
            python setup.py sdist bdist_wheel
            pipenv install dist/*.whl
            pipenv install pytest
#      - run:
#          command: |  # Run test suite
#            pipenv run pytest
  test_pypi_publish:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout  # checkout source code to working directory
      - run: cp .pypirc ~/
      - run: echo "password = $TESTPYPI_API_KEY" >> ~/.pypirc
      - run:
          command: |  # create whl, install twine and publish to Test PyPI
            sudo apt update && sudo apt upgrade -y && sudo apt install -y git
            sudo pip install setuptools --upgrade
            sudo pip install --upgrade pip
            sudo pip install pipenv
            python setup.py sdist bdist_wheel
            pipenv install twine
            pipenv run twine upload --repository testpypi dist/*
  pypi_publish:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # create whl, install twine and publish to PyPI
            sudo apt update && sudo apt upgrade -y && sudo apt install -y git
            sudo pip install setuptools --upgrade
            sudo pip install --upgrade pip
            sudo pip install pipenv
            python setup.py sdist bdist_wheel
            pipenv install twine
#            pipenv run twine upload dist/*
workflows:
  build_test_publish:
    jobs:
      - build_test
      - test_pypi_publish:
          requires:
            - build_test
          filters:
            branches:
              only:
                - develop
      - pypi_publish:
          requires:
            - build_test
          filters:
            branches:
              only:
                - master